make docker-compose-lite.yaml the up and running env (#159)
* add activate host for docker-compose-lite.yaml

* log to stderr instead of file for docker-compose-lite.yaml

* polish the console service to avoid confusion

diff --git a/docker-compose-lite.yaml b/docker-compose-lite.yaml
--- a/docker-compose-lite.yaml
+++ b/docker-compose-lite.yaml
@@ -11,7 +11,11 @@ services:
       - --port=9559
       - --ws_http_port=19559
       - --data_path=/data/meta
-      - --log_dir=/logs
+      # - --log_dir=/logs
+      # log to stderr not file
+      - --logtostderr=true
+      - --redirect_stdout=false
+      # log to stderr not file
       - --v=0
       - --minloglevel=0
     healthcheck:
@@ -26,7 +30,7 @@ services:
       - 19560
     volumes:
       - ./data/meta0:/data/meta
-      - ./logs/meta0:/logs
+      # - ./logs/meta0:/logs
     networks:
       - nebula-net
     restart: on-failure
@@ -37,7 +41,6 @@ services:
     image: docker.io/vesoft/nebula-storaged:nightly
     environment:
       USER: root
-      TZ:   "${TZ}"
     command:
       - --meta_server_addrs=metad0:9559
       - --local_ip=storaged0
@@ -45,7 +48,11 @@ services:
       - --port=9779
       - --ws_http_port=19779
       - --data_path=/data/storage
-      - --log_dir=/logs
+      # - --log_dir=/logs
+      # log to stderr not file
+      - --logtostderr=true
+      - --redirect_stdout=false
+      # log to stderr not file
       - --v=0
       - --minloglevel=0
     depends_on:
@@ -62,7 +69,7 @@ services:
       - 19780
     volumes:
       - ./data/storage0:/data/storage
-      - ./logs/storage0:/logs
+      # - ./logs/storage0:/logs
     networks:
       - nebula-net
     restart: on-failure
@@ -73,14 +80,17 @@ services:
     image: docker.io/vesoft/nebula-graphd:nightly
     environment:
       USER: root
-      TZ:   "${TZ}"
     command:
       - --meta_server_addrs=metad0:9559
       - --port=9669
       - --local_ip=graphd
       - --ws_ip=graphd
       - --ws_http_port=19669
-      - --log_dir=/logs
+      # - --log_dir=/logs
+      # log to stderr not file
+      - --logtostderr=true
+      - --redirect_stdout=false
+      # log to stderr not file
       - --v=0
       - --minloglevel=0
     depends_on:
@@ -95,13 +105,58 @@ services:
       - 9669:9669
       - 19669:19669
       - 19670
-    volumes:
-      - ./logs/graph:/logs
+    # volumes:
+    #   - ./logs/graph:/logs
     networks:
       - nebula-net
     restart: on-failure
     cap_add:
       - SYS_PTRACE
+
+  storage-activator:
+    # This is just a script to activate storaged for the first time run by calling nebula-console
+    # Refer to https://docs.nebula-graph.io/master/4.deployment-and-installation/manage-storage-host/#activate-storaged
+    # If you like to call console via docker, run:
+
+    # docker run --rm -ti --network host vesoft/nebula-console:nightly -addr 127.0.0.1 -port 9669 -u root -p nebula
+
+    image: docker.io/vesoft/nebula-console:nightly
+    entrypoint: ""
+    environment:
+      ACTIVATOR_RETRY: ${ACTIVATOR_RETRY:-30}
+    command: 
+      - sh
+      - -c
+      - |
+        for i in `seq 1 $$ACTIVATOR_RETRY`; do
+          nebula-console -addr graphd -port 9669 -u root -p nebula -e 'ADD HOSTS "storaged0":9779' 1>/dev/null 2>/dev/null;
+          if [[ $$? == 0 ]]; then
+            echo "✔️ Storage activated successfully.";
+            break;
+          else
+            output=$$(nebula-console -addr graphd -port 9669 -u root -p nebula -e 'ADD HOSTS "storaged0":9779' 2>&1);
+            if echo "$$output" | grep -q "Existed"; then
+              echo "✔️ Storage already activated, Exiting...";
+              break;
+            fi
+          fi;
+          if [[ $$i -lt $$ACTIVATOR_RETRY ]]; then
+            echo "⏳ Attempting to activate storaged, attempt $$i/$$ACTIVATOR_RETRY... It's normal to take some attempts before storaged is ready. Please wait.";
+          else
+            echo "❌ Failed to activate storaged after $$ACTIVATOR_RETRY attempts. Please check MetaD, StorageD logs. Or restart the storage-activator service to continue retry.";
+            echo "ℹ️ Error during storage activation:"
+            echo "=============================================================="
+            echo "$$output"
+            echo "=============================================================="
+            break;
+          fi;
+          sleep 5;
+        done && tail -f /dev/null;
+
+    depends_on:
+      - graphd
+    networks:
+      - nebula-net
 
 networks:
   nebula-net:
